# Generated by Django 3.2.3 on 2022-01-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_auto_20220109_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='users', verbose_name='Аватар'),
        ),
    ]
